---
settings:
  name: BlueXP ransomware protection
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: de-de,us-en,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: BlueXP Dokumente zum Ransomware-Schutz
    url: "/index.html"
  - title: Versionshinweise
    entries:
    - title: Neuerungen beim BlueXP Ransomware-Schutz
      url: "/whats-new.html"
  - title: Los geht's
    entries:
    - title: Mehr zu BlueXP Ransomware-Schutz
      url: "/concept-ransomware-protection.html"
    - title: Voraussetzungen
      url: "/rp-start-prerequisites.html"
    - title: Schnellstart
      url: "/rp-start-quick-start.html"
    - title: BlueXP Ransomware-Schutz einrichten
      url: "/rp-start-setup.html"
    - title: Nutzen Sie den Ransomware-Schutz von BlueXP
      url: "/rp-start-login.html"
    - title: Lizenzierung einrichten
      url: "/rp-start-licenses.html"
    - title: Workloads erkennen
      url: "/rp-start-discover.html"
    - title: Konfigurieren Sie Sicherungsziele und aktivieren Sie die Bedrohungserkennung
      url: "/rp-use-settings.html"
    - title: Häufig gestellte Fragen
      url: "/rp-start-faq.html"
  - title: Nutzen Sie BlueXP Ransomware-Schutz
    entries:
    - title: Nutzen Sie die Übersicht zum BlueXP Ransomware-Schutz
      url: "/rp-use-overview.html"
    - title: Über das Dashboard können Sie den Workload-Zustand anzeigen
      url: "/rp-use-dashboard.html"
    - title: Schutz von Workloads
      entries:
      - title: Schützen Sie Workloads mit Strategien zum Schutz vor Ransomware
        url: "/rp-use-protect.html"
      - title: Scannen Sie nach personenbezogenen Daten
        url: "/rp-use-protect-classify.html"
    - title: Reagieren Sie auf eine erkannte Warnung
      url: "/rp-use-alert.html"
    - title: Wiederherstellung nach einem Ransomware-Angriff
      url: "/rp-use-recover.html"
    - title: Berichte herunterladen
      url: "/rp-use-reports.html"
  - section: support
  - title: Referenz
    entries:
    - title: 'Rollenbasierte Zugriffssteuerung: Privileges'
      url: "/rp-reference-roles.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
