---
sidebar: sidebar 
permalink: rp-reference-roles.html 
keywords: ransomware protection, protect against ransomware attacks, anti-ransomware, role-based access control, rbac, role, permission, access rights, organization,project,account 
summary: 'Beim BlueXP  Ransomware-Schutz wird mittels rollenbasierter Zugriffssteuerung (Role Based Access Control, RBAC) der Zugriff jedes Benutzers auf spezifische Funktionen und Aktionen festgelegt. Der Service verwendet spezifische Rollen für den BlueXP  Ransomware-Schutz (RPS).' 
---
= BlueXP  Ransomware-Schutz, rollenbasierter Zugriff auf Funktionen
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Der BlueXP  Ransomware-Schutz verwendet Rollen, um den Zugriff jedes Benutzers auf spezifische Funktionen und Aktionen zu regeln.

Der Service verwendet die folgenden Rollen, die speziell auf den BlueXP  Ransomware-Schutz zugeschnitten sind.

* *Ransomware-Schutz admin*: Verwalten Sie Aktionen auf den Registerkarten Schützen, Warnungen, Wiederherstellen, Einstellungen und Berichte.
* *Ransomware Protection Viewer*: Workload-Daten anzeigen, Warnungsdaten anzeigen, Wiederherstellungsdaten herunterladen und Berichte herunterladen.


Die BlueXP -Plattform für alle BlueXP -Services verwendet folgende Rollenarten:

* *Plattform-Rollen* ermöglichen Ihnen, Benutzer zu verwalten, sie Ressourcen zuzuweisen und ihnen Rollen zusammen mit anderen plattformweiten Aktionen zu geben.
+

TIP: Für die Entdeckung in BlueXP  Ransomware-Schutz, müssen Sie über die * Organisation Admin * Rolle zusätzlich zu der * Ransomware-Schutz Admin * Rolle.

* *Data Services Rollen* sind auf einen bestimmten Datendienst beschränkt. Je nach Ihrer Aufgabe können Sie mehrere Datenservice-Rollen haben. BlueXP  Ransomware-Schutz ist einer der BlueXP  Datenservices.


Andere Rollen der BlueXP  Plattform werden als Zuschauer beim BlueXP  Ransomware-Schutz behandelt. Die Rolle *Organisations-Viewer* ermöglicht es Ihnen beispielsweise, die Schutzpläne anzuzeigen, erlaubt Ihnen aber keine Aktionen im BlueXP  Ransomware-Schutz.

Weitere Informationen zu allen Rollen der BlueXP -Plattform finden Sie unter https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["Die BlueXP -Installations- und Administrationsdokumentation"^].

Die folgende Tabelle zeigt die Aktionen, die jede BlueXP  Ransomware-Schutzrolle durchführen kann.

[cols="40,20a,20a"]
|===
| Funktion und Aktion | Administrator für Ransomware-Schutz | Viewer für Ransomware-Schutz 


| Dashboard und alle Registerkarten anzeigen  a| 
Ja.
 a| 
Ja.



| Aktualisieren Sie auf dem Dashboard den Empfehlungsstatus  a| 
Ja.
 a| 
Nein



| Kostenlos testen  a| 
Ja.
 a| 
Nein



| Beginnen Sie mit der Erkennung von Workloads  a| 
Ja.
 a| 
Nein



| Neuerkennung von Workloads einleiten  a| 
Ja.
 a| 
Nein



3+| *Auf der Registerkarte Schutz*: 


| Schutzpläne hinzufügen, ändern oder löschen  a| 
Ja.
 a| 
Nein



| Schutz von Workloads  a| 
Ja.
 a| 
Nein



| Identifizierung des Risikos sensibler Daten  a| 
Ja.
 a| 
Nein



| Listen Sie Schutzpläne und Details auf  a| 
Ja.
 a| 
Ja.



| Listen Sie Schutzgruppen auf  a| 
Ja.
 a| 
Ja.



| Details zu Schutzgruppen anzeigen  a| 
Ja.
 a| 
Ja.



| Schutzgruppe erstellen, bearbeiten oder löschen  a| 
Ja.
 a| 
Nein



| Download von Daten  a| 
Ja.
 a| 
Ja.



3+| *Auf der Registerkarte Warnungen*: 


| Anzeigen von Warnmeldungen und Warnungsdetails  a| 
Ja.
 a| 
Ja.



| Bearbeiten Sie den Ereignisstatus  a| 
Ja.
 a| 
Nein



| Alarm für Wiederherstellung markieren  a| 
Ja.
 a| 
Nein



| Anzeigen von Vorfalldetails  a| 
Ja.
 a| 
Ja.



| Schließen oder Auflösen von Aufzungen  a| 
Ja.
 a| 
Nein



| Benutzer blockieren  a| 
Ja.
 a| 
Nein



| Vollständige Liste der betroffenen Dateien abrufen  a| 
Ja.
 a| 
Nein



| Warnmeldungen herunterladen  a| 
Ja.
 a| 
Ja.



3+| *Auf der Registerkarte Wiederherstellen*: 


| Betroffene Dateien herunterladen  a| 
Ja.
 a| 
Nein



| Restore-Workload  a| 
Ja.
 a| 
Nein



| Wiederherstellungsdaten herunterladen  a| 
Ja.
 a| 
Ja.



| Berichte herunterladen  a| 
Ja.
 a| 
Ja.



3+| *Auf der Registerkarte Einstellungen*: 


| Backup-Ziele hinzufügen oder ändern  a| 
Ja.
 a| 
Nein



| Backup-Ziele auflisten  a| 
Ja.
 a| 
Ja.



| Verbundene SIEM-Ziele anzeigen  a| 
Ja.
 a| 
Ja.



| SIEM-Ziele hinzufügen oder ändern  a| 
Ja.
 a| 
Nein



| Verbinden Sie Workload-Sicherheitsziele  a| 
Ja.
 a| 
Nein



| Anzeigen des Verbindungsstatus für die Workload-Sicherheit  a| 
Ja.
 a| 
Ja.



| Trennen Sie die Workload-Sicherheitsziele  a| 
Ja.
 a| 
Nein



| Konfigurieren Sie den Bereitschaftsbohrer  a| 
Ja.
 a| 
Nein



| Bereitschaftsbohrer starten  a| 
Ja.
 a| 
Nein



| Bereitschaftsbohrer zurücksetzen  a| 
Ja.
 a| 
Nein



| Bereitschaftsübung bearbeiten  a| 
Ja.
 a| 
Nein



| Prüfen Sie den Status der Bereitschaftsübung  a| 
Ja.
 a| 
Ja.



| Aktualisieren Sie die Ermittlungskonfiguration  a| 
Ja.
 a| 
Nein



| Anzeigen der Ermittlungskonfiguration  a| 
Ja.
 a| 
Ja.



3+| *Auf der Registerkarte Berichte*: 


| Berichte herunterladen  a| 
Ja.
 a| 
Ja.

|===