---
sidebar: sidebar 
permalink: rp-start-prerequisites.html 
keywords: what are bluexp ransomware protection requirements, bluexp ransomware protection, ransomware protection prerequisites 
summary: 'Erste Schritte mit BlueXP zum Ransomware-Schutz: Verifizieren Sie den Support für Ihre Umgebung, Ihren Netzwerkzugriff, Ihre Anmeldung und Ihren Webbrowser.' 
---
= Voraussetzungen für den BlueXP Ransomware-Schutz
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/get-started/


[role="lead"]
Erste Schritte mit BlueXP zum Ransomware-Schutz: Überprüfen Sie Ihre Betriebsumgebung, Ihre Anmeldung, Ihren Netzwerkzugriff und Ihren Webbrowser.

Um den BlueXP  Ransomware-Schutz zu nutzen, müssen Sie folgende Voraussetzungen erfüllen.



== In BlueXP 

* Ein BlueXP -Benutzerkonto mit Organisationsadministrator-Privileges zur Erkennung von Ressourcen.
* Eine BlueXP -Organisation mit mindestens einem aktiven BlueXP  Connector, der mit On-Premises-ONTAP-Clustern verbunden oder mit Cloud Volumes ONTAP in AWS oder in Azure verbunden ist.
* Mindestens eine BlueXP  Arbeitsumgebung mit einem NetApp On-Premises ONTAP Cluster oder Cloud Volume ONTAP in AWS oder Azure (mit NAS- oder CIFS-Protokollen).
+
** ONTAP- oder Cloud Volume ONTAP-Cluster mit ONTAP OS Version 9.11.1 oder höher werden unterstützt.
** Wenn Ihre On-Premises-ONTAP-Cluster oder Cloud Volume ONTAP in AWS oder in der Azure Cloud noch nicht in BlueXP  integriert sind, benötigen Sie einen BlueXP  Connector.
+
Siehe https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html["Erfahren Sie, wie Sie einen BlueXP -Anschluss konfigurieren"] und https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["Standard-BlueXP Anforderungen erfüllt"^].

+

NOTE: Wenn Sie mehrere BlueXP  Connectors in einer einzelnen BlueXP -Organisation haben, durchsucht der Ransomware-Schutz-Service von BlueXP  ONTAP-Ressourcen über alle Connectors hinaus, die derzeit in der BlueXP -Benutzeroberfläche ausgewählt sind.







== Im ONTAP 9.11.1 und höher

* Eine Lizenz für den autonomen Schutz vor NetApp Ransomware, die durch BlueXP Ransomware-Schutz verwendet wird und je nach verwendeter ONTAP-Version auf der lokalen ONTAP-Instanz aktiviert wird. Siehe https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["Autonome Ransomware-Schutz – Übersicht"^].
+

NOTE: Die allgemeine Version des BlueXP Ransomware-Schutzes im Gegensatz zu der Preview-Version umfasst eine Lizenz für die NetApp Technologie zum autonomen Ransomware-Schutz. Siehe https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["Autonome Ransomware-Schutz – Übersicht"^] Entsprechende Details.

+
Weitere Informationen zur Lizenzierung finden Sie unter link:concept-ransomware-protection.html["Mehr zu BlueXP Ransomware-Schutz"].

* Für die Anwendung von Sicherungskonfigurationen (wie die Aktivierung von Autonomous Ransomware Protection und anderen) ist für den BlueXP  Ransomware-Schutz Administratorberechtigungen im ONTAP-Cluster erforderlich. Das ONTAP Cluster sollte nur mit den Anmeldedaten des ONTAP Cluster Admin-Benutzers aufgenommen werden.
* Wenn der ONTAP Cluster bereits mit den Anmeldedaten eines nicht-Admin-Benutzers in BlueXP  integriert ist, müssen die Berechtigungen eines nicht-Admin-Benutzers durch die erforderlichen Berechtigungen aktualisiert werden, indem Sie sich bei dem ONTAP-Cluster anmelden, der auf dieser Seite beschrieben wird.




== Für Daten-Backups

* Ein Konto in NetApp StorageGRID, AWS S3 oder Azure Blob für Backup-Ziele und die Zugriffsberechtigungen.
+
Weitere Informationen finden Sie im https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions.html["Berechtigungsliste für AWS, Azure oder S3"^] .

* Der BlueXP  Backup- und Recovery-Service muss in der Arbeitsumgebung nicht aktiviert werden.
+
Der BlueXP Ransomware-Schutzservice unterstützt Sie bei der Konfiguration eines Backup-Ziels über die Einstellungsoption. Siehe link:rp-use-settings.html["Einstellungen konfigurieren"].





== Aktualisieren Sie nicht-Admin-Benutzerberechtigungen in einer ONTAP-Arbeitsumgebung

Führen Sie die folgenden Schritte aus, wenn Sie nicht-Administratorrechte für eine bestimmte Arbeitsumgebung aktualisieren müssen.

. Melden Sie sich bei BlueXP  an, und suchen Sie nach der Arbeitsumgebung, die die ONTAP-Benutzerberechtigungen aktualisieren muss.
. Doppelklicken Sie auf die Arbeitsumgebung, um Details anzuzeigen.
. Klicken Sie auf *Weitere Informationen anzeigen*, die den Benutzernamen anzeigen.
. Loggen Sie sich über den Admin-Benutzer bei der ONTAP-Cluster-CLI ein.
. Zeigt die vorhandenen Rollen für diesen Benutzer an. Geben Sie Ein:
+
[listing]
----
security login show -user-or-group-name <username>
----
. Ändern Sie die Rolle für den Benutzer. Geben Sie Ein:
+
[listing]
----
security login modify -user-or-group-name <username> -application console|http|ontapi|ssh|telnet -authentication-method password -role admin
----
. Kehren Sie zur BlueXP  Ransomware-Schutz-UI zurück, um sie zu verwenden.

