---
sidebar: sidebar 
permalink: rp-start-setup.html 
keywords: bluexp, ransomware protection, aws, azure 
summary: Um den Ransomware-Schutz von BlueXP zu nutzen, führen Sie ein paar Schritte aus, um ihn einzurichten. 
---
= BlueXP Ransomware-Schutz einrichten
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Um den Ransomware-Schutz von BlueXP zu nutzen, führen Sie ein paar Schritte aus, um ihn einzurichten.

Bevor Sie beginnen, überprüfen Sie link:rp-start-prerequisites.html["Voraussetzungen"] Und stellen Sie sicher, dass Ihre Umgebung bereit ist.



== Bereiten Sie das Sicherungsziel vor

Bereiten Sie eines der folgenden Sicherungsziele vor:

* NetApp StorageGRID
* Amazon Web Services
* Google Cloud Platform
* Microsoft Azure


Nachdem Sie Optionen im Backup-Ziel selbst konfiguriert haben, werden Sie sie später im BlueXP Ransomware-Schutzservice als Backup-Ziel konfigurieren. Informationen zum Konfigurieren des Backup-Ziels für BlueXP -Ransomware-Schutz finden Sie unter link:rp-use-settings.html["Konfigurieren Sie Sicherungsziele"].



=== StorageGRID als Backup-Ziel vorbereiten

Wenn Sie StorageGRID als Sicherungsziel verwenden möchten, finden Sie weitere Informationen unter https://docs.netapp.com/us-en/storagegrid-117/index.html["StorageGRID-Dokumentation"^] Weitere Informationen zu StorageGRID.



=== AWS als Backup-Ziel vorbereiten

* Richten Sie ein Konto in AWS ein.
* Konfigurieren https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions.html["AWS Berechtigungen"^] In AWS migriert.


Weitere Informationen zum Management Ihres AWS Storage in BlueXP finden Sie unter https://docs.netapp.com/us-en/bluexp-setup-admin/task-viewing-amazon-s3.html["Amazon S3 Buckets managen"^].



=== Azure als Backup-Ziel vorbereiten

* Richten Sie ein Konto in Azure ein.
* Konfigurieren https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions.html["Azure-Berechtigungen"^] In Azure aus.


Weitere Informationen zum Management von Azure Storage in BlueXP finden Sie unter https://docs.netapp.com/us-en/bluexp-blob-storage/task-view-azure-blob-storage.html["Managen Sie Ihre Azure Storage-Konten"^].



== BlueXP einrichten

Der nächste Schritt besteht darin, BlueXP und den BlueXP Ransomware-Schutzservice einzurichten.

Überprüfen https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-standard-mode.html["BlueXP-Anforderungen für den Standardmodus"^].



=== Connector in BlueXP erstellen

Wenden Sie sich an Ihren NetApp Vertriebsmitarbeiter, um diesen Service auszuprobieren oder zu nutzen. Wenn Sie dann den BlueXP Connector verwenden, erhalten Sie auch die entsprechenden Funktionen für den Ransomware-Schutzservice.

Um einen Connector in BlueXP zu erstellen, bevor Sie den Dienst nutzen, wenden Sie sich an Ihren BlueXP-Organisationsadministrator, der über die Berechtigung zum Erstellen von Connectors verfügt, und lesen Sie die BlueXP-Dokumentation, die beschreibt  https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html["So erstellen Sie einen BlueXP Connector"^] .


NOTE: Wenn Sie mehrere BlueXP Connectors verwenden, scannt der Service Daten über alle Connectors hinaus, die derzeit in der BlueXP UI angezeigt werden. Dieser Service erkennt alle Projekte und alle Connectors, die mit dieser Organisation verbunden sind.
