---
sidebar: sidebar 
permalink: rp-start-faq.html 
keywords: ransomware protection faq, ransomware protection frequently asked questions 
summary: Diese FAQ kann Ihnen helfen, wenn Sie nur nach einer schnellen Antwort auf eine Frage suchen. 
---
= Häufig gestellte Fragen zum BlueXP Ransomware-Schutz
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Diese FAQ kann Ihnen helfen, wenn Sie nur nach einer schnellen Antwort auf eine Frage suchen.



== Datenzugriff

*Wie sieht die BlueXP URL zum Ransomware-Schutz aus?*
Geben Sie für die URL in einem Browser Folgendes ein: https://console.bluexp.netapp.com/["https://console.bluexp.netapp.com/"^] Um auf die BlueXP Konsole zuzugreifen.

*Benötigen Sie eine Lizenz für den Einsatz von BlueXP Ransomware-Schutz?*

Sie können die folgenden Lizenztypen verwenden:

* Melden Sie sich für eine kostenlose 90-Tage-Testversion an.
* Mit Amazon Web Services (AWS) Marketplace besteht ein Pay-as-you-go-Abonnement (PAYGO).
* Bring-Your-Own-License (BYOL) bei einer NetApp Lizenzdatei (NLF), die Sie von Ihrem NetApp Vertriebsmitarbeiter erhalten. Sie können die Seriennummer der Lizenz verwenden, um das BYOL in der Digital Wallet von BlueXP zu aktivieren.


*Wie aktivieren Sie den BlueXP Ransomware-Schutz?*
BlueXP für den Ransomware-Schutz ist keine Unterstützung erforderlich. Die Option zum Schutz vor Ransomware wird in der linken Navigation von BlueXP automatisch aktiviert.

Um den Service zu testen, müssen Sie sich anmelden oder sich mit Ihrem Vertriebsmitarbeiter von NetApp in Verbindung setzen. Wenn Sie dann den BlueXP Connector verwenden, werden Ihnen die entsprechenden Funktionen für den Service bereitgestellt.

**Ist BlueXP Ransomware-Schutz im standardmäßigen, eingeschränkten und privaten Modus verfügbar?**
Derzeit ist BlueXP Ransomware-Schutz nur im Standardmodus verfügbar. Bleiben Sie dran für mehr.

Eine Erläuterung zu diesen Modi in allen BlueXP Services finden Sie unter https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["BlueXP Implementierungsmodi"^].

**Wie werden Zugriffsberechtigungen behandelt?**
Nur Account-Administratoren können den Service initiieren und Workloads erkennen (da dies die Verpflichtung zur Nutzung einer Ressource beinhaltet). Nachfolgende Interaktionen können von jeder Rolle durchgeführt werden.

**Welche Geräteauflösung ist am besten?**
Die empfohlene Geräteauflösung für den BlueXP Ransomware-Schutz ist 1.920 x 1.080 oder höher.

**Welcher Browser sollte ich verwenden?**
Jeder moderne Browser funktioniert.



== Interaktion mit anderen Diensten

*Kennt der BlueXP Ransomware-Schutz die in NetApp ONTAP vorgenommenen Schutzeinstellungen?*
Ja, der Ransomware-Schutz von BlueXP erkennt Snapshot Zeitpläne, die in ONTAP festgelegt sind.

*Wenn Sie eine Richtlinie mit BlueXP Ransomware-Schutz festlegen, müssen Sie nur an diesem Service zukünftige Änderungen vornehmen?*
Wir empfehlen Ihnen, Richtlinienänderungen am BlueXP Ransomware-Schutzservice vorzunehmen.



== Workloads

**Was macht eine Arbeitsbelastung aus?**
Ein Workload umfasst alle Volumes, die von einer einzelnen Applikationsinstanz verwendet werden. Eine auf ora3.host.com bereitgestellte Oracle DB-Instanz kann beispielsweise vol1 und vol2 für ihre Daten und Protokolle verwenden. Diese Volumes bilden zusammen den Workload für diese spezifische Instanz der Oracle DB-Instanz.

*Wie priorisiert der Ransomware-Schutz von BlueXP Workload-Daten?*
Die Datenpriorität wird durch die erstellten Snapshot-Kopien und geplanten Backups bestimmt.

Die Workload-Priorität wird durch die Snapshot-Häufigkeit bestimmt.

link:rp-use-protect.html["Informieren Sie sich über Priorität oder Wichtigkeit von Workloads"].

**Neues Volumen hinzugefügt, erscheint aber noch nicht**
Wenn Sie der Umgebung ein neues Volume hinzugefügt haben, initiieren Sie die Erkennung erneut und wenden Sicherungsrichtlinien an, um das neue Volume zu schützen.

**Das Dashboard zeigt nicht alle meine Workloads an. Was könnte falsch sein?**
Derzeit werden nur NFS- und CIFS-Volumes unterstützt. ISCSI-Volumes und andere nicht unterstützte Konfigurationen werden herausgefiltert und werden nicht im Dashboard angezeigt.



== Sicherungsrichtlinien

*Bestehen BlueXP Ransomware-Richtlinien parallel zu den anderen Arten von Workload-Richtlinien?*
Derzeit unterstützt BlueXP Backup und Recovery (Cloud Backup) eine Backup-Richtlinie pro Volume. Nun, BlueXP Backup und Recovery sowie BlueXP Ransomware-Schutz nutzen gemeinsam Backup-Richtlinien.

Snapshot-Kopien sind nicht beschränkt und können separat von jedem Service hinzugefügt werden.
