---
sidebar: sidebar 
permalink: rp-start-prerequisites.html 
keywords: what are bluexp ransomware protection requirements, bluexp ransomware protection, ransomware protection prerequisites 
summary: 'Erste Schritte mit BlueXP zum Ransomware-Schutz: Verifizieren Sie den Support für Ihre Umgebung, Ihren Netzwerkzugriff, Ihre Anmeldung und Ihren Webbrowser.' 
---
= Voraussetzungen für den BlueXP Ransomware-Schutz
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/get-started/


[role="lead"]
Erste Schritte mit BlueXP zum Ransomware-Schutz: Überprüfen Sie Ihre Betriebsumgebung, Ihre Anmeldung, Ihren Netzwerkzugriff und Ihren Webbrowser.

Um BlueXP vor Ransomware zu schützen, benötigen Sie folgende Voraussetzungen:

* Ein Konto in NetApp StorageGRID oder AWS S3 für Backup-Ziele und die festgelegten Zugriffsberechtigungen
+
Siehe https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions.html["AWS-Berechtigungsliste"^] Entsprechende Details.

* ONTAP 9.11.1 und höher
+
** ONTAP-Berechtigungen für Cluster-Admin
** Eine Lizenz für den autonomen Schutz vor NetApp Ransomware, die durch BlueXP Ransomware-Schutz verwendet wird und je nach verwendeter ONTAP-Version auf der lokalen ONTAP-Instanz aktiviert wird. Siehe https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["Autonome Ransomware-Schutz – Übersicht"^].
+

NOTE: Die allgemeine Version des BlueXP Ransomware-Schutzes im Gegensatz zu der Preview-Version umfasst eine Lizenz für die NetApp Technologie zum autonomen Ransomware-Schutz. Siehe https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["Autonome Ransomware-Schutz – Übersicht"^] Entsprechende Details.

+
Weitere Informationen zur Lizenzierung finden Sie unter link:concept-ransomware-protection.html["Mehr zu BlueXP Ransomware-Schutz"].



* In BlueXP:
+
** Eine BlueXP Arbeitsumgebung mit lokalem NetApp Storage (über NAS- oder CIFS-Protokolle)
** In BlueXP muss ein BlueXP Connector je Virtual Private Cloud (VPC) oder für eine On-Premises-Region eingerichtet werden. Siehe https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html["BlueXP Dokumentation zur Konfiguration des Connectors"^].
+

NOTE: Wenn Sie mehrere BlueXP Connectors verwenden, scannt der Service Daten über alle Connectors hinaus, die derzeit in der BlueXP UI angezeigt werden.

** Ein BlueXP Konto mit mindestens einem aktiven Connector, der mit On-Premises-ONTAP-Clustern verbunden ist. Alle Quell- und Arbeitsumgebungen müssen sich auf demselben BlueXP Konto befinden.
** Ein BlueXP Benutzerkonto mit Administratorrechten für das Erkennen von Ressourcen
** Eine BlueXP Arbeitsumgebung mit lokalem NetApp Storage (über NAS- oder CIFS-Protokolle)
** https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["Standard-BlueXP Anforderungen erfüllt"^]





NOTE: Der BlueXP Backup- und Recovery-Service muss in der Arbeitsumgebung nicht mehr bereits aktiviert sein. Der BlueXP Ransomware-Schutzservice unterstützt Sie bei der Konfiguration eines Backup-Ziels über die Einstellungsoption. Siehe link:rp-use-settings.html["Einstellungen konfigurieren"].
