---
sidebar: sidebar 
permalink: rp-start-prerequisites.html 
keywords: what are bluexp ransomware protection requirements, bluexp ransomware protection, ransomware protection prerequisites 
summary: 'Erste Schritte mit BlueXP zum Ransomware-Schutz: Verifizieren Sie den Support für Ihre Umgebung, Ihren Netzwerkzugriff, Ihre Anmeldung und Ihren Webbrowser.' 
---
= Voraussetzungen für den BlueXP Ransomware-Schutz
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/get-started/


[role="lead"]
Erste Schritte mit BlueXP zum Ransomware-Schutz: Überprüfen Sie Ihre Betriebsumgebung, Ihre Anmeldung, Ihren Netzwerkzugriff und Ihren Webbrowser.

Um den BlueXP ransomware protection zu verwenden, benötigen Sie die Voraussetzungen.



== In BlueXP 

* Ein BlueXP -Benutzerkonto bei Organization Admin Privileges zur Erkennung von Ressourcen.
* Eine BlueXP Organisation mit mindestens einem aktiven BlueXP Connector, der eine Verbindung zu lokalen ONTAP Clustern oder zu Cloud Volumes ONTAP in AWS oder Azure herstellt.
* Der BlueXP -Konnektor muss den Container in einem aktiven Zustand haben `cloudmanager-ransomware-protection`.
* Mindestens eine BlueXP Arbeitsumgebung mit einem lokalen NetApp ONTAP Cluster oder Cloud Volumes ONTAP in AWS oder Azure. Der BlueXP ransomware protection unterstützt sowohl NAS- (NFS und SMB) als auch SAN-Protokolle (iSCSI, FC und NVMe).
+
** ONTAP oder Cloud Volumes ONTAP Cluster mit ONTAP OS Version 9.11.1 oder höher werden unterstützt.
+

NOTE: SAN-Workloads werden nur in ONTAP 9.17.1 und höher unterstützt.

** Wenn Ihre lokalen ONTAP Cluster oder Cloud Volumes ONTAP in AWS oder in der Azure-Cloud noch nicht in BlueXP integriert sind, benötigen Sie einen BlueXP Connector.
+
Siehe https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html["Erfahren Sie, wie Sie einen BlueXP -Anschluss konfigurieren"] und https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["Standard-BlueXP Anforderungen erfüllt"^].

+

NOTE: Wenn Sie mehrere BlueXP  Connectors in einer einzelnen BlueXP -Organisation haben, durchsucht der Ransomware-Schutz-Service von BlueXP  ONTAP-Ressourcen über alle Connectors hinaus, die derzeit in der BlueXP -Benutzeroberfläche ausgewählt sind.







== Im ONTAP 9.11.1 und höher

* Eine ONTAP One Lizenz ist auf der lokalen ONTAP Instanz aktiviert.
* Eine Lizenz für den autonomen Schutz vor NetApp Ransomware, die durch BlueXP Ransomware-Schutz verwendet wird und je nach verwendeter ONTAP-Version auf der lokalen ONTAP-Instanz aktiviert wird. Siehe https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["Autonome Ransomware-Schutz – Übersicht"^].
+

NOTE: Die allgemeine Version des BlueXP Ransomware-Schutzes im Gegensatz zu der Preview-Version umfasst eine Lizenz für die NetApp Technologie zum autonomen Ransomware-Schutz. Siehe https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["Autonome Ransomware-Schutz – Übersicht"^] Entsprechende Details.

+
Weitere Informationen zur Lizenzierung finden Sie unter link:concept-ransomware-protection.html["Mehr zu BlueXP Ransomware-Schutz"].

* Für die Anwendung von Sicherungskonfigurationen (wie die Aktivierung von Autonomous Ransomware Protection und anderen) ist für den BlueXP  Ransomware-Schutz Administratorberechtigungen im ONTAP-Cluster erforderlich. Das ONTAP Cluster sollte nur mit den Anmeldedaten des ONTAP Cluster Admin-Benutzers aufgenommen werden.
* Wenn der ONTAP Cluster bereits mit den Anmeldedaten eines nicht-Admin-Benutzers in BlueXP  integriert ist, müssen die Berechtigungen eines nicht-Admin-Benutzers durch die erforderlichen Berechtigungen aktualisiert werden, indem Sie sich bei dem ONTAP-Cluster anmelden, der auf dieser Seite beschrieben wird.




== Für Daten-Backups

* Ein Konto in NetApp StorageGRID, AWS S3, Azure Blob oder Google Cloud Platform für Sicherungsziele und die festgelegten Zugriffsberechtigungen.
+
Weitere Informationen finden Sie im https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions.html["Berechtigungsliste für AWS, Azure oder S3"^] .

* Der BlueXP  Backup- und Recovery-Service muss in der Arbeitsumgebung nicht aktiviert werden.
+
Der BlueXP Ransomware-Schutzservice unterstützt Sie bei der Konfiguration eines Backup-Ziels über die Einstellungsoption. Siehe link:rp-use-settings.html["Einstellungen konfigurieren"].





== Aktualisieren Sie nicht-Admin-Benutzerberechtigungen in einer ONTAP-Arbeitsumgebung

Führen Sie die folgenden Schritte aus, wenn Sie nicht-Administratorrechte für eine bestimmte Arbeitsumgebung aktualisieren müssen.

. Melden Sie sich bei BlueXP  an, und suchen Sie nach der Arbeitsumgebung, die die ONTAP-Benutzerberechtigungen aktualisieren muss.
. Doppelklicken Sie auf die Arbeitsumgebung, um Details anzuzeigen.
. Wählen Sie *Zusätzliche Informationen anzeigen*, um den Benutzernamen anzuzeigen.
. Loggen Sie sich über den Admin-Benutzer bei der ONTAP-Cluster-CLI ein.
. Zeigt die vorhandenen Rollen für diesen Benutzer an. Geben Sie Ein:
+
[listing]
----
security login show -user-or-group-name <username>
----
. Ändern Sie die Rolle für den Benutzer. Geben Sie Ein:
+
[listing]
----
security login modify -user-or-group-name <username> -application console|http|ontapi|ssh|telnet -authentication-method password -role admin
----
. Kehren Sie zur BlueXP  Ransomware-Schutz-UI zurück, um sie zu verwenden.

