= Erkennen von ungewöhnlichem Benutzerverhalten mit Data Infrastructure Insights Storage Workload Security
:allow-uri-read: 




=== Erkennen von ungewöhnlichem Benutzerverhalten mit Data Infrastructure Insights Storage Workload Security

Mit dieser Version können Sie Storage Workload Security von Data Infrastructure Insights verwenden, um ungewöhnliches Benutzerverhalten in Ihren Storage-Workloads zu erkennen. Diese Funktion hilft Ihnen dabei, potenzielle Sicherheitsbedrohungen zu erkennen und potenziell böswillige Benutzer zu blockieren, um Ihre Daten zu schützen.

Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-alert.html["Reagieren Sie auf einen erkannten Ransomware-Alarm"].

Bevor Sie Data Infrastructure Insights Storage Workload Security zur Erkennung von ungewöhnlichem Benutzerverhalten verwenden, müssen Sie die Option über die Option BlueXP  Ransomware Protection *Settings* konfigurieren.

Siehe https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-settings.html["Konfigurieren Sie BlueXP Ransomware-Schutzeinstellungen"].



=== Wählen Sie die zu erdeckende und zu schützende Workloads aus

Mit dieser Version können Sie nun Folgendes tun:

* Wählen Sie in jedem Connector die Arbeitsumgebungen aus, in denen Sie Workloads erkennen möchten. Diese Funktion könnte für Sie von Vorteil sein, wenn Sie bestimmte Workloads in Ihrer Umgebung schützen möchten und keine anderen.
* Während der Workload-Erkennung können Sie die automatische Erkennung von Workloads pro Connector aktivieren. Mit dieser Funktion können Sie die Workloads auswählen, die Sie schützen möchten.
* Ermittlung neu erstellter Workloads für zuvor ausgewählte Arbeitsumgebungen.


Siehe https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-discover.html["Workloads erkennen"].
