= Unterstützung von Amazon FSX für NetApp ONTAP
:allow-uri-read: 




=== Unterstützung von Amazon FSX für NetApp ONTAP

Dieser Release unterstützt Amazon FSX für NetApp ONTAP. Diese Funktion hilft Ihnen mit BlueXP  Ransomware-Schutz dabei, Ihre FSX for ONTAP-Workloads zu schützen.

FSX for ONTAP ist ein vollständig gemanagter Service, der die Leistung von NetApp ONTAP Storage in der Cloud bereitstellt. Er bietet dieselben Funktionen, Performance- und Administrationsfunktionen, die Sie vor Ort nutzen, sowie die Agilität und Skalierbarkeit eines nativen AWS-Service.

Am Workflow für Ransomware-Schutz von BlueXP  wurden folgende Änderungen vorgenommen:

* Bestandsaufnahme umfasst Workloads in FSX for ONTAP 9.15 Arbeitsumgebungen.
* Auf der Registerkarte „Schutz“ werden Workloads in FSX für ONTAP-Umgebungen angezeigt. In dieser Umgebung sollten Sie Backup-Vorgänge mithilfe des FSX für ONTAP-Backup-Service durchführen. Sie können diese Workloads mit BlueXP  Snapshots zum Schutz vor Ransomware wiederherstellen.
+

TIP: Backup-Richtlinien für Workloads, die auf FSX for ONTAP ausgeführt werden, können nicht in BlueXP  festgelegt werden. Alle bestehenden Backup-Richtlinien in Amazon FSX für NetApp ONTAP bleiben unverändert.

* Warnungsvorfälle zeigen die neue Arbeitsumgebung von FSX for ONTAP.


Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/bluexp-ransomware-protection/concept-ransomware-protection.html["Erfahren Sie mehr über BlueXP  Ransomware-Schutz und Arbeitsumgebungen"].

Informationen zu den unterstützten Optionen finden Sie im https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-reference-limitations.html["Einschränkungen beim BlueXP  Schutz vor Ransomware"].



=== BlueXp-Zugriffsrolle erforderlich

Sie benötigen jetzt eine der folgenden Zugriffsrollen, um den BlueXP-Ransomware-Schutz anzuzeigen, zu erkennen oder zu verwalten: Organisationsadministrator, Ordner- oder Projektadministrator, Ransomware-Schutzadministrator oder Ransomware-Schutz-Betrachter.

https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["Erfahren Sie mehr über BlueXP-Zugriffsrollen für alle Dienste"^].
