= Simulieren Sie einen Angriff und reagieren Sie darauf
:allow-uri-read: 




=== Simulieren Sie einen Angriff und reagieren Sie darauf

Mit dieser Version können Sie einen Ransomware-Angriff simulieren, um Ihre Reaktion auf eine Ransomware-Warnung zu testen. Diese Funktion hilft Ihnen dabei, sich im Falle eines echten Ransomware-Angriffs auf Sie vorzubereiten, indem Sie Warnmeldungs-, Reaktions- und Recovery-Prozesse testen.

Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-simulate.html["Machen Sie sich eine Übung zur Vorbereitung auf einen Ransomware-Angriff"].



=== Verbesserungen am Ermittlungsprozess

Diese Version enthält Verbesserungen an den Prozessen zur selektiven Bestandsaufnahme und erneuten Bestandsaufnahme:

* Mit diesem Release können Sie neu erstellte Workloads erkennen, die den zuvor ausgewählten Arbeitsumgebungen hinzugefügt wurden.
* Sie können in dieser Version auch _New_ Arbeitsumgebungen auswählen. Diese Funktion unterstützt Sie beim Schutz neuer Workloads, die zu Ihrer Umgebung hinzugefügt werden.
* Sie können diese Erkennungsprozesse während des Erkennungsvorgangs zunächst oder über die Option Einstellungen durchführen.


Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-discover.html["Ermittlung neu erstellter Workloads für zuvor ausgewählte Arbeitsumgebungen"] und https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-settings.html["Konfigurieren Sie Funktionen mit der Option Einstellungen"].



=== Warnmeldungen werden ausgegeben, wenn eine hohe Verschlüsselung erkannt wird

Mit dieser Version können Sie Warnmeldungen anzeigen, wenn eine hohe Verschlüsselung bei Ihren Workloads erkannt wird, selbst ohne Änderungen an der Dateierweiterung. Diese Funktion, die ARP-KI (ONTAP Autonomous Ransomware Protection) nutzt, hilft Ihnen bei der Ermittlung von Workloads, die dem Risiko von Ransomware-Angriffen ausgesetzt sind. Verwenden Sie diese Funktion, und laden Sie die gesamte Liste der betroffenen Dateien mit oder ohne Erweiterungsänderungen herunter.

Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-alert.html["Reagieren Sie auf einen erkannten Ransomware-Alarm"].
